### ISSUE TITLE
Try out Sustain

### ISSUE THREAD

**Issue by infertux** [infertux/zeyple#13]
https://github.com/joshuavial/sustain

**Comment by TabTwo** [comment]
a distributed payment system?
Is this SPAM?

**Comment by infertux** [comment]
Haha, not spam at all @TabTwo. I just figured it might be a good way to incentivise people to contribute more to the project. There has been some feature requests that have been lying around for years (especially #2 and #5). I only maintain this project on my spare time and I'd love more help from skilled Pythonistas out there.
