### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by acatton** [infertux/zeyple#16]
[This is good advice for system administrators](https://lobste.rs/s/1vwpqj/the_worst_possible_devops_advice/comments/673mpf#c_673mpf)

The advice rightfully say that you shouldn't download random things from the internet.

[I think tags should be signed](https://git-scm.com/book/tr/v2/Git-Tools-Signing-Your-Work). This will improve security for system administrators directly using your code, and future debian packagers.

**Comment by infertux** [comment]
Releases are already signed, see footnote at https://github.com/infertux/zeyple/blob/master/INSTALL.md#fn-1. Great point though :)

**Comment by acatton** [comment]
Oops... I should have read the readme :) .

**Comment by infertux** [comment]
Well it's kinda hidden in a separate INSTALL.md file to be fair. Otherwise I would have said RTFM :stuck_out_tongue_winking_eye:
