### ISSUE TITLE
Handle attachements (multipart) using PGP/MIME

### ISSUE THREAD

**Issue by infertux** [infertux/zeyple#2]

**Comment by TabTwo** [comment]
Any news on this?
Would be really great to have encrypted multipart.

**Comment by Nithanim** [comment]
I am looking forward to this too!
I looked at some other programs providing encryption too but zeyple didn't look and in fact was not complicated to setup. It works like a charm, thank you! :)

**Comment by Nithanim** [comment]
acatton, I clone your current state (https://github.com/acatton/zeyple/commit/398cde082a955f173afd06c1b8b5a7bbfcd94da2) of your Moving towards 1.1.0 branch. A plaintext mail is still working but as soon I tried with html (and additionally with an attachment beforehand) I only got an "empty" mail back. It is displayed as empty both in the web-interface of my provider and in Thunderbird. However the exported .eml contains the encrypted message.
I am unsure why it is behaving that way but these files might help you to figure it out https://www.dropbox.com/sh/awbjoff0naycmv3/AADK3hsmubOLU_4jDZ2pqWnXa?lst

**Comment by acatton** [comment]
@Nithanim thank you for the feedback. It is a real by in my code, I have to read the PGP/MIME RFC to understand exactly how multipart emails should be encrypted. I'll fix that ASAP.

**Comment by Nithanim** [comment]
@acatton Multipart is my most desired feature since most of the mails I get are html and might have some sort of attachment. Since I don't know python, the bindings to gpg or the RFC i am no use there so I thought I would do I that way at least :P 
Thank you so much for your effort in getting this working!
