### ISSUE TITLE
Thunderbird trouble to decrypt php sent messages.

### ISSUE THREAD

**Issue by Nithanim** [infertux/zeyple#21]
I have a cms installed on on my webserver that (most likley) uses the php-mailer to send emails. However, thunderbird refuses to decrypt them properly and somehow hangs (hard to describe, it won't decrypt any more emails) instead.
I am not sure how or where to get more debug information but [this files may help you](https://www.dropbox.com/sh/ax6bnc96178rgr0/AADeaF8chBfvWjDTRkhHwMnua?dl=0).

I am using https://github.com/infertux/zeyple/commit/86a3c27900d0327bb25fe1125c654e6eaf43c9e6.

**Comment by infertux** [comment]
Dammit, who would have thought it'd be so hard to encrypt emails... :stuck_out_tongue_winking_eye: 

I think I managed to reproduce your issue: Thunderbird hangs with _"Loading Message..."_, the message box stays blank, and if run `ps`, I can see `gpg --decrypt [...]` hanging too.

I tweaked something and it fixed it for me. Could you try [this version](https://raw.githubusercontent.com/infertux/zeyple/fix_issue_21/zeyple/zeyple.py) and let me know? Thanks!

**Comment by Nithanim** [comment]
Yes, perfect! It works now with your fix!
I can finally stop decrypting every email manually ;)

**Comment by infertux** [comment]
Wow, that's awesome! Thanks. I'll just wait a day or two to make sure it didn't break anything else now ;)
