### ISSUE TITLE
special charachets are not shown correclty in Outlook 2013 or Thunderbird

### ISSUE THREAD

**Issue by cscholz** [infertux/zeyple#23]
In the German language we've the special characters ü,ö,ß which were not readable after an encrpytion with zeplye in version 1.1.0.
I've seen that this version contains already a fix for Thunderbird (del out_message["Content-Transfer-Encoding"]).
Nevertheless I had charachter issues with Outlook 2013, roundcube as webmail and Thunderbird for testing.

Below I've attached a proposal (patch related to v.1.1.0) which fixed the issue in my environment.

BR Christian

> [zeyple_charset.txt](https://github.com/infertux/zeyple/files/82803/zeyple_charset.txt)

**Comment by infertux** [comment]
Sorry for taking so long @cscholz, I finally added your changes. Thank you for the feedback!
