### ISSUE TITLE
support PGP/MIME

### ISSUE THREAD

**Issue by morph027** [infertux/zeyple#28]
As some of our messages are HTML mails and users really don't want to see the tags, we should probably implement PGP/MIME which should be able to handle this.

Might have a look here: https://github.com/zenhack/python-gpgmime

**Comment by infertux** [comment]
Hmm I'm not sure I understand. Zeyple already uses [PGP/MIME](https://github.com/infertux/zeyple/blob/master/zeyple/zeyple.py#L191-L202) in theory. Are you saying it isn't implemented properly?

**Comment by infertux** [comment]
Got this similar bug report by email:

> Turns out this is caused by mails that aren't using multipart, but a different content-type. The mails producing this in my case come from mattermost. You can see the code here: https://github.com/mattermost/platform/blob/master/utils/mail.go

**Comment by infertux** [comment]
Hi @morph027,

Thanks for your patience. This should be fixed now (please reopen the issue if not).

Here's a helper script to upgrade to v1.2.0: https://github.com/infertux/zeyple/blob/master/upgrade.sh

**Comment by morph027** [comment]
Hey, nice....good i'm about to re-setup my mail gateway ;) Will report back. Thank you!

**Comment by morph027** [comment]
![zeyple](https://cloud.githubusercontent.com/assets/600106/20828185/7a8ba2c2-b876-11e6-81db-b9d6f1a00de2.png)

Confirmed, testing HTML messages from my Gitlab ...

**Comment by infertux** [comment]
Super! Thanks for the feedback.
