### ISSUE TITLE
HTML mail evaluates as non-multipart

### ISSUE THREAD

**Issue by inputvalidation** [infertux/zeyple#34]
I have a HTML mail that causes is_multipart() to return False. Looking at the zeyple code it is then converted to a text/plain multipart and encrypted afterwards. After decrypting the mail my client happily shows me the HTML as text.

```
<...snip...headers>
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!doctype html>
<...snip...more HTML>
```

**Comment by infertux** [comment]
I doubt it but #41 might have fixed this. Could you try the latest version from https://github.com/infertux/zeyple/blob/master/zeyple/zeyple.py?

**Comment by infertux** [comment]
Please try version 1.2.2 and reopen this issue if you're still having problems. You may use [upgrade.sh](https://github.com/infertux/zeyple/blob/master/upgrade.sh).
