### ISSUE TITLE
Support manual key import?

### ISSUE THREAD

**Issue by dominic-p** [infertux/zeyple#53]
Sorry if this is already covered, but I didn't see any documentation on how to manually import a key for a recipient (without using a key server). Maybe this will be covered in #30?

Anyway, thanks for sharing this great software. :)

**Comment by infertux** [comment]
This should work: `sudo -u zeyple gpg --homedir /var/lib/zeyple/keys --import <key-file.gpg>`. Please reopen the issue if not.

**Comment by dominic-p** [comment]
That did it. Thanks!
