### ISSUE TITLE
Script died with status 1

### ISSUE THREAD

**Issue by DrauzJu** [infertux/zeyple#56]
Hi,
first of all thanks for the useful plugin! Unfortunately I get the following error in the logs while trying to send an encrypted mail (using the `sendmail` command):

`Command died with status 1: "/usr/local/bin/zeyple.py".
    Command output: Traceback (most recent call last):   File
    "/usr/local/bin/zeyple.py", line 285, in <module>
    zeyple.process_message(message, recipients)   File
    "/usr/local/bin/zeyple.py", line 123, in process_message
    self._send_message(out_message, recipient)   File
    "/usr/local/bin/zeyple.py", line 269, in _send_message
    self.config.get('relay', 'port'))   File "/usr/lib/python2.7/smtplib.py",
    line 256, in __init__     (code, msg) = self.connect(host, port)   File
    "/usr/lib/python2.7/smtplib.py", line 316, in connect     self.sock =
    self._get_socket(host, port, self.timeout)   File
    "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket     return
    socket.create_connection((host, port), timeout)   File
    "/usr/lib/python2.7/socket.py", line 557, in create_connection     for res
    in getaddrinfo(host, port, 0, SOCK_STREAM): socket.error: getaddrinfo()
    argument 2 must be integer or string`

Can somebody help me? 

OS: Ubuntu 16.04
Python 2.7.12

Thanks and regards!

**Comment by infertux** [comment]
According to `getaddrinfo(host, port, 0, SOCK_STREAM): socket.error: getaddrinfo() argument 2 must be integer or string`, it seems the port is invalid. Please make sure it looks [like this](https://github.com/infertux/zeyple/blob/master/zeyple/zeyple.conf.example#L9) and post the content of your `zeyple.conf` file if you're still having issues. Thanks.

**Comment by DrauzJu** [comment]
Output of `cat /etc/zeyple.conf` looks like this:
```
[zeyple]
log_file = /var/log/zeyple.log

[gpg]
home = /var/lib/zeyple/keys

[relay]
host = localhost
port = 10026

```
(So the default)

As a workaround, I just hardcoded the values in the zeyple.py script, then it works fine

**Comment by infertux** [comment]
This is strange, could you please add `print type(port)` to the script to check what type `port` is. It should be an `int`.

**Comment by DrauzJu** [comment]
I get this output: `<type 'unicode'>`
Is there something wrong with the encoding of my configuration file?

**Comment by infertux** [comment]
Not sure but could you try to download the file again?

`wget https://raw.githubusercontent.com/infertux/zeyple/master/zeyple/zeyple.conf.example -O /etc/zeyple.conf`

**Comment by DrauzJu** [comment]
No, didn't work, type is still the same

**Comment by infertux** [comment]
Interesting, could you try this change to make sure the port is casted as an `int`:

```diff
diff --git i/zeyple/zeyple.py w/zeyple/zeyple.py
index 2f0c227..6329389 100755
--- i/zeyple/zeyple.py
+++ w/zeyple/zeyple.py
@@ -266,7 +266,7 @@ class Zeyple:
         logging.info("Sending message %s", message['Message-id'])
 
         smtp = smtplib.SMTP(self.config.get('relay', 'host'),
-                            self.config.get('relay', 'port'))
+                            self.config.getint('relay', 'port'))
 
         smtp.sendmail(message['From'], recipient, message.as_string())
         smtp.quit()
```

**Comment by DrauzJu** [comment]
Thanks, that worked! I created a PR
