### ISSUE TITLE
Debian package fails to configure if pip is not insatlled

### ISSUE THREAD

**Issue by HaraldWilhelmi** [infertux/zeyple#66]
If a Debian package is created including fpm/after-install.sh the configuration of the package
fails with this error message if pip is not insatlled:

/var/lib/dpkg/info/tng-zeyple.postinst: 46: /var/lib/dpkg/info/tng-zeyple.postinst: pip: not found
/var/lib/dpkg/info/tng-zeyple.postinst: 46: /var/lib/dpkg/info/tng-zeyple.postinst: pip: not found

IMHO the change to this file introduced in commit 52ff087bb06937320d95ee5485379dfaf0150121
is strange: Dependencies should be handled in fpm/create and not in a post install script.

**Comment by infertux** [comment]
> Dependencies should be handled in fpm/create and not in a post install script.

Yes good catch. Just want to [double check](https://github.com/infertux/zeyple/pull/64#discussion_r339139428) with @DrauzJu first before we remove the `pip install` command though.
